### ISSUE TITLE
Add: Treasure class

### ISSUE THREAD

**Issue by winterhotlatte** [cpuabuse/dungeon-together#19]
## Description

Class location is `src\app\server\entities\exclusive\chests\treasure.ts`.

**Comment by yanocv** [comment]
The path in the description does not add up to the actual path in the source code. There is no chests folder.

**Comment by winterhotlatte** [comment]
@yanocv

> The path in the description does not add up to the actual path in the source code. There is no chests folder.

Used `treasure` as path instead.
It makes more sense, as chests sounds more like storage chests as well.

Anyways, it is merged so closing for now.
