### ISSUE TITLE
Add: Trap class functionality

### ISSUE THREAD

**Issue by oliverjiu** [cpuabuse/dungeon-together#41]
## Description

We don't have anything inside the class trap, we should fill it.

## Goals

- [x] The `trap.ts` should move a folder above
- [x] Make the class trap abstract
- [x] Add properties to trap:
	- [x] Visibility - whether the player can see the trap or not
	- [x] Damage - the trap can cause damage to the player

**Comment by yanocv** [comment]
#41 has resolved this issue.
